/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class Calculator {
    public static void main(String[] args) {
        Double result = 2.5 + 2.5;
        System.out.printf("The result is %f \n", result);
    }

    public Integer add(Integer int1, Integer int2) {
        Integer sum = int1 + int2;
        return sum;
    }

    
}
